# Generated by Django 3.2.6 on 2021-12-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20211213_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='unit_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
