# Generated by Django 3.2.6 on 2021-10-29 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.IntegerField(choices=[(0, 'English')], default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='profiles/covers/')),
                ('mobile', models.CharField(max_length=255, unique=True)),
                ('accepted_terms', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_token', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('invitation_code', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.IntegerField(choices=[(0, 'Not Set'), (1, 'Male'), (2, 'Female')], default=0)),
                ('life_time_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('total_savings', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('abandoned_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('potential_savings', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_login', models.BooleanField(default=True)),
                ('first_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_country', to='locations.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'profiles',
            },
        ),
    ]
