# Generated by Django 3.2.6 on 2022-01-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
