# Generated by Django 3.2.6 on 2021-11-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
