# Generated by Django 3.2.6 on 2021-11-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
