# Generated by Django 3.2.6 on 2021-12-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
