# Generated by Django 3.2.6 on 2021-12-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
