# Generated by Django 3.2.6 on 2021-12-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocodes', '0002_promocode_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='number',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promocode',
            name='per_person',
            field=models.SmallIntegerField(default=0),
        ),
    ]
