# Generated by Django 3.2.6 on 2021-12-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promocodes', '0003_auto_20211213_0812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='per_person',
            new_name='per_user',
        ),
    ]
