# Generated by Django 3.2.6 on 2021-12-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='slug',
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='passcode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
