# Generated by Django 3.2.6 on 2021-12-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglists', '0002_auto_20211205_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='slug',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
