# Generated by Django 3.2.6 on 2021-12-07 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoppinglists', '0003_shoppinglist_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High'), (3, 'Emergency')], default=0),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Available'), (1, 'Reserved'), (2, 'Bought')], default=0),
        ),
    ]
