# Generated by Django 3.2.6 on 2021-12-19 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shoppinglists', '0005_auto_20211218_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglistcontributor',
            name='role',
        ),
        migrations.AddField(
            model_name='shoppinglistcontributor',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contributor_role', to='auth.group'),
            preserve_default=False,
        ),
    ]
