# Generated by Django 3.2.6 on 2021-12-26 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoppinglists', '0007_auto_20211225_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistcontributor',
            name='invitee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shoppinglistcontributor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoppinglist_invitee', to=settings.AUTH_USER_MODEL),
        ),
    ]
