# Generated by Django 3.2.6 on 2022-01-04 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoppinglists', '0008_auto_20211226_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_expired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_products', to='shoppinglists.shoppinglistitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reserves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserved Product',
                'verbose_name_plural': 'Reserved Products',
                'db_table': 'gift_reservations',
                'ordering': ['created_at'],
            },
        ),
    ]
