# Generated by Django 3.2.6 on 2021-12-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20211218_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='extra_context',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
