# Generated by Django 3.2.6 on 2021-10-29 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField()),
                ('data', models.CharField(blank=True, max_length=255, null=True)),
                ('ttl', models.CharField(blank=True, max_length=255, null=True)),
                ('expiration', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.CharField(blank=True, max_length=255, null=True)),
                ('sound', models.CharField(blank=True, max_length=255, null=True)),
                ('badge', models.IntegerField(blank=True, max_length=255, null=True)),
                ('channelId', models.CharField(blank=True, max_length=255, null=True)),
                ('categoryId', models.CharField(blank=True, max_length=255, null=True)),
                ('mutableContent', models.BooleanField(default=False)),
                ('service', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('send_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('response', models.JSONField(blank=True, null=True)),
                ('service_push_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Push Notification',
                'verbose_name_plural': 'Push Notifications',
                'db_table': 'push_notifications',
            },
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_push_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Token',
                'verbose_name_plural': 'Push Tokens',
                'db_table': 'push_tokens',
            },
        ),
    ]
