# Generated by Django 3.2.6 on 2021-12-04 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['ordering', 'title'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
