# Generated by Django 3.2.6 on 2021-12-13 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promocodes', '0004_rename_per_person_promocode_per_user'),
        ('cart', '0003_auto_20211213_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promocodes', to='promocodes.redemption'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_promocodes', to='promocodes.redemption'),
        ),
    ]
