# Generated by Django 3.2.6 on 2022-01-04 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglists', '0008_auto_20211226_0908'),
        ('cart', '0004_auto_20211213_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='shoppinglist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifts', to='shoppinglists.shoppinglistitem'),
        ),
    ]
