# Generated by Django 3.2.6 on 2021-12-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('ordering', models.SmallIntegerField(default=0)),
                ('link_type', models.SmallIntegerField(choices=[(0, 'Website'), (1, 'Facebook'), (2, 'Twitter'), (3, 'Instagram'), (4, 'LinkedIn'), (5, 'Pinterest')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'db_table': 'links',
                'ordering': ('ordering',),
            },
        ),
    ]
